In [1]:
import sqlite3, pandas as pd

In [32]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

df_users = pd.DataFrame({
    'id': pd.Series([1,2,3], dtype='int32'),
    'name': pd.Series(['Alice', 'Bob', 'Charlie'], dtype='string'),
})

df_sales = pd.DataFrame({
    'user_id': pd.Series([1,2,1,4], dtype='int32'),
    'amount': pd.Series([100,200,150,300], dtype='int32'),
})

df_users.to_sql(name='users', con=engine, index=False)
df_sales.to_sql(name='sales', con=engine, index=False)

4

In [33]:
query = """
    SELECT users.name, SUM(COALESCE(sales.amount, 0)) as total_amount
    FROM users
    LEFT JOIN sales ON users.id = sales.user_id
    GROUP BY users.id
"""

pd.read_sql(query, con=engine)

      name  total_amount
0    Alice           250
1      Bob           200
2  Charlie             0

In [34]:
query = """
    SELECT COALESCE(users.name, 'Unknown') as user_name, SUM(COALESCE(sales.amount, 0)) as total_amount
    FROM sales
    LEFT JOIN users ON users.id = sales.user_id
    GROUP BY user_id
"""

pd.read_sql(query, con=engine)

  user_name  total_amount
0     Alice           250
1       Bob           200
2   Unknown           300